steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/sunny-buttress-448517-f8/srishti-100912171:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/sunny-buttress-448517-f8/srishti-100912171:$COMMIT_SHA'

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-cloud-run-service'  # Update this with your actual service name
      - '--image=gcr.io/sunny-buttress-448517-f8/srishti-100912171:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/sunny-buttress-448517-f8/srishti-100912171:$COMMIT_SHA'
